# Generated by Django 2.1.3 on 2018-11-06 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('price', models.FloatField()),
                ('image', models.FileField(upload_to='')),
                ('status', models.CharField(choices=[('PUB', 'Published'), ('RES', 'Reserved'), ('SLD', 'Sold')], max_length=3)),
            ],
        ),
    ]
