# Generated by Django 2.1.3 on 2018-11-06 23:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='last_modification',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='ad',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
